-- Generated by the Organizer Library (Fri Jan 15 15:19:46 2021)
return {
    [1]={
        ["log_name"]="prosilio belt", 
        ["id"]=10827, 
        ["name"]="prosilio belt", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="souveran handschuhs +1", 
        ["count"]=1, 
        ["id"]=27023, 
        ["name"]="souv. handsch. +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [3]={
        ["log_name"]="carmine cuisses +1", 
        ["count"]=1, 
        ["id"]=27207, 
        ["name"]="carmine cuisses +1", 
        ["augments"]={
            [1]="Accuracy+20", 
            [2]="Attack+12", 
            [3]="\"Dual Wield\"+6"
        }
    }, 
    [4]={
        ["log_name"]="flume belt", 
        ["id"]=10819, 
        ["name"]="flume belt", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="leyline gloves", 
        ["count"]=1, 
        ["id"]=27135, 
        ["name"]="leyline gloves", 
        ["augments"]={
            [1]="Accuracy+15", 
            [2]="Mag. Acc.+15", 
            [3]="\"Mag.Atk.Bns.\"+15", 
            [4]="\"Fast Cast\"+3"
        }
    }
}