-- Generated by the Organizer Library (Fri Jan 15 15:19:46 2021)
return {
    [1]={
        ["log_name"]="homiliary", 
        ["id"]=22268, 
        ["name"]="homiliary", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="sapience orb", 
        ["id"]=22252, 
        ["name"]="sapience orb", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="pixie hairpin +1", 
        ["id"]=26696, 
        ["name"]="pixie hairpin +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="impatiens", 
        ["id"]=19761, 
        ["name"]="impatiens", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="ghastly tathlum +1", 
        ["id"]=21344, 
        ["name"]="ghastly tathlum +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="malevolence", 
        ["id"]=20595, 
        ["name"]="malevolence", 
        ["count"]=1
    }
}