-- Generated by the Organizer Library (Fri Jan 15 15:19:46 2021)
return {
    [1]={
        ["log_name"]="cascade belt", 
        ["id"]=15909, 
        ["name"]="cascade belt", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="mecistopins mantle", 
        ["id"]=27596, 
        ["name"]="mecisto. mantle", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="chaac belt", 
        ["id"]=28450, 
        ["name"]="chaac belt", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="fucho-no-obi", 
        ["id"]=28452, 
        ["name"]="fucho-no-obi", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="incanter's torque", 
        ["id"]=26016, 
        ["name"]="incanter's torque", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="voltsurge torque", 
        ["id"]=28354, 
        ["name"]="voltsurge torque", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="solemnity cape", 
        ["id"]=26245, 
        ["name"]="solemnity cape", 
        ["count"]=1
    }
}