-- Generated by the Organizer Library (Fri Jan 15 15:19:46 2021)
return {
    [1]={
        ["log_name"]="brilliance", 
        ["count"]=1, 
        ["id"]=20705, 
        ["name"]="brilliance", 
        ["augments"]={
            [1]="Shield skill +10", 
            [2]="Divine magic skill +15", 
            [3]="Enmity+7", 
            [4]="DMG:+15"
        }
    }, 
    [2]={
        ["log_name"]="sulevia's leggings +2", 
        ["id"]=25946, 
        ["name"]="sulev. leggings +2", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="souveran diechlings +1", 
        ["count"]=1, 
        ["id"]=27199, 
        ["name"]="souv. diechlings +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [4]={
        ["log_name"]="odyssean helm", 
        ["count"]=1, 
        ["id"]=25640, 
        ["name"]="odyssean helm", 
        ["augments"]={
            [1]="Accuracy+21 Attack+21", 
            [2]="STR+8", 
            [3]="Accuracy+12"
        }
    }, 
    [5]={
        ["log_name"]="odyssean helm", 
        ["count"]=1, 
        ["id"]=25640, 
        ["name"]="odyssean helm", 
        ["augments"]={
            [1]="\"Fast Cast\"+3", 
            [2]="Pet: VIT+5", 
            [3]="Accuracy+15 Attack+15", 
            [4]="Mag. Acc.+11 \"Mag.Atk.Bns.\"+11"
        }
    }, 
    [6]={
        ["log_name"]="ochain", 
        ["id"]=16193, 
        ["name"]="ochain", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="souveran schuhs +1", 
        ["count"]=1, 
        ["id"]=27375, 
        ["name"]="souveran schuhs +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [8]={
        ["log_name"]="volte moufles", 
        ["id"]=23720, 
        ["name"]="volte moufles", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="valorous mail", 
        ["count"]=1, 
        ["id"]=25717, 
        ["name"]="valorous mail", 
        ["augments"]={
            [1]="Accuracy+25 Attack+25", 
            [2]="Weapon skill damage +4%", 
            [3]="Accuracy+10", 
            [4]="Attack+12"
        }
    }, 
    [10]={
        ["log_name"]="odyssean gauntlets", 
        ["count"]=1, 
        ["id"]=27138, 
        ["name"]="odyssean gauntlets", 
        ["augments"]={
            [1]="INT+11", 
            [2]="\"Mag.Atk.Bns.\"+25", 
            [3]="Accuracy+10 Attack+10", 
            [4]="Mag. Acc.+20 \"Mag.Atk.Bns.\"+20"
        }
    }, 
    [11]={
        ["log_name"]="founder's hose", 
        ["count"]=1, 
        ["id"]=28191, 
        ["name"]="founder's hose", 
        ["augments"]={
            [1]="MND+2", 
            [2]="Mag. Acc.+4", 
            [3]="Breath dmg. taken -1%"
        }
    }, 
    [12]={
        ["log_name"]="flamma gambieras +2", 
        ["id"]=25953, 
        ["name"]="flam. gambieras +2", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="malignance sword", 
        ["id"]=21635, 
        ["name"]="malignance sword", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="rudianos's mantle", 
        ["count"]=1, 
        ["id"]=26252, 
        ["name"]="rudianos's mantle", 
        ["augments"]={
            [1]="HP+60", 
            [2]="Eva.+20 /Mag. Eva.+20", 
            [3]="Mag. Evasion+5", 
            [4]="Enmity+10", 
            [5]="Phys. dmg. taken-10%"
        }
    }, 
    [15]={
        ["log_name"]="rudianos's mantle", 
        ["count"]=1, 
        ["id"]=26252, 
        ["name"]="rudianos's mantle", 
        ["augments"]={
            [1]="INT+20", 
            [2]="Eva.+20 /Mag. Eva.+20", 
            [3]="Mag. Evasion+10", 
            [4]="\"Fast Cast\"+10"
        }
    }, 
    [16]={
        ["log_name"]="ygnas's resolve +1", 
        ["id"]=28368, 
        ["name"]="ygnas's resolve +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="creed collar", 
        ["id"]=11595, 
        ["name"]="creed collar", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="sacro breastplate", 
        ["id"]=25767, 
        ["name"]="sacro breastplate", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="odyssean greaves", 
        ["count"]=1, 
        ["id"]=27494, 
        ["name"]="odyssean greaves", 
        ["augments"]={
            [1]="Pet: Accuracy+10 Pet: Rng. Acc.+10", 
            [2]="Mag. Acc.+18 \"Mag.Atk.Bns.\"+18", 
            [3]="Magic burst dmg.+12%"
        }
    }, 
    [20]={
        ["log_name"]="sacro gorget", 
        ["id"]=26039, 
        ["name"]="sacro gorget", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="knightly earring", 
        ["id"]=14758, 
        ["name"]="knightly earring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="kubira meikogai", 
        ["id"]=26959, 
        ["name"]="kubira meikogai", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="regal gauntlets", 
        ["id"]=25824, 
        ["name"]="regal gauntlets", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="odyssean cuisses", 
        ["count"]=1, 
        ["id"]=25840, 
        ["name"]="odyssean cuisses", 
        ["augments"]={
            [1]="MND+7", 
            [2]="Magic Damage +7", 
            [3]="\"Treasure Hunter\"+1", 
            [4]="Mag. Acc.+20 \"Mag.Atk.Bns.\"+20"
        }
    }, 
    [25]={
        ["log_name"]="odyssean cuisses", 
        ["count"]=1, 
        ["id"]=25840, 
        ["name"]="odyssean cuisses", 
        ["augments"]={
            [1]="\"Fast Cast\"+6", 
            [2]="\"Mag.Atk.Bns.\"+12"
        }
    }, 
    [26]={
        ["log_name"]="flamma zucchetto +2", 
        ["id"]=25569, 
        ["name"]="flam. zucchetto +2", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="sulevia's gauntlets +2", 
        ["id"]=25828, 
        ["name"]="sulev. gauntlets +2", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="asklepian belt", 
        ["id"]=26327, 
        ["name"]="asklepian belt", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="founder's corona", 
        ["id"]=27764, 
        ["name"]="founder's corona", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="aegis", 
        ["id"]=16197, 
        ["name"]="aegis", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="diemer gorget", 
        ["id"]=27522, 
        ["name"]="diemer gorget", 
        ["count"]=1
    }
}