-- Generated by the Organizer Library (Fri Jan 15 15:19:46 2021)
return {
    [1]={
        ["log_name"]="cessance earring", 
        ["id"]=27541, 
        ["name"]="cessance earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="ishvara earring", 
        ["id"]=27537, 
        ["name"]="ishvara earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="friomisi earring", 
        ["id"]=28514, 
        ["name"]="friomisi earring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="white rarab cap +1", 
        ["id"]=25679, 
        ["name"]="wh. rarab cap +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="dark ring", 
        ["id"]=14644, 
        ["name"]="dark ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="mendicant's earring", 
        ["id"]=28474, 
        ["name"]="mendi. earring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="andoaa earring", 
        ["id"]=28506, 
        ["name"]="andoaa earring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="weatherspoon ring", 
        ["id"]=27582, 
        ["name"]="weather. ring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="trux earring", 
        ["id"]=28515, 
        ["name"]="trux earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="thureous earring", 
        ["id"]=27546, 
        ["name"]="thureous earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="nourishing earring", 
        ["id"]=28484, 
        ["name"]="nourish. earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="Attack+4", 
            [2]="TP Bonus +250"
        }
    }
}